//Vinícius Horácio Marques Póvoa
package com.mycompany.programajframe;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;


public class JFrame extends javax.swing.JFrame {

    private ArrayList<Integer> numerosDigitados = new ArrayList<>();

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();

        OKButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                 OKButtonActionPerformed(evt);  
            }
        });

        exibirButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                exibirButtonActionPerformed(evt);
            }
        });

        calcularButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                calcularButtonActionPerformed(evt);
            }
        });
    }

    private void OKButtonActionPerformed(ActionEvent evt) {
        String numeroString = numeroText.getText();
        if (numeroString.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe um número.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            int numero = Integer.parseInt(numeroString);
            numerosDigitados.add(numero);
            numeroText.setText("");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Informe um número válido.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void exibirButtonActionPerformed(ActionEvent evt) {
        if (numerosDigitados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhum número foi digitado ainda.", "Informação", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        StringBuilder numerosText = new StringBuilder();
        for (int numero : numerosDigitados) {
            numerosText.append(numero).append(" ");
        }
        
        int menor = Integer.MAX_VALUE;
        int maior = Integer.MIN_VALUE;
        int soma = 0;
        
        
        
        for (int numero : numerosDigitados) {
            menor = Math.min(menor, numero);
            maior = Math.max(maior, numero);
            soma += numero;
            
        }
        
        double media = (double) soma / numerosDigitados.size();
        menorText.setText(Integer.toString(menor));
        maiorText.setText(Integer.toString(maior));
        mediaText.setText(Double.toString(media));
        
        JOptionPane.showMessageDialog(this,
            "Números Digitados: " + numerosText.toString() + "\n",
            "Exibir Resultados",
            JOptionPane.INFORMATION_MESSAGE);
    }

    private void calcularButtonActionPerformed(ActionEvent evt) {
        String valoresString = valoresText.getText();
        String opcaoSelecionada = (String) opcoesCB.getSelectedItem();
        
        if (valoresString.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe os valores separados.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String[] valores = valoresString.split(" ");
        ArrayList<Integer> numeros = new ArrayList<>();
        
        for (String valor : valores) {
            try {
                int numero = Integer.parseInt(valor);
                numeros.add(numero);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Informe valores numéricos válidos.", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        
        int resultado;
        
        if (opcaoSelecionada.equals("Somar")) {
            resultado = somarNumeros(numeros);
        } else {
            resultado = multiplicarNumeros(numeros);
        }
        
        JOptionPane.showMessageDialog(this, "Resultado: " + resultado, "Cálculo", JOptionPane.INFORMATION_MESSAGE);
    }
    
    private int somarNumeros(ArrayList<Integer> numeros) {
        int soma = 0;
        for (int numero : numeros) {
            soma += numero;
        }
        return soma;
    }
    
    private int multiplicarNumeros(ArrayList<Integer> numeros) {
        int produto = 1;
        for (int numero : numeros) {
            produto *= numero;
        }
        return produto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numeroText = new javax.swing.JTextField();
        maiorText = new javax.swing.JTextField();
        menorText = new javax.swing.JTextField();
        mediaText = new javax.swing.JTextField();
        valoresText = new javax.swing.JTextField();
        opcoesCB = new javax.swing.JComboBox<>();
        calcularButton = new javax.swing.JButton();
        OKButton = new javax.swing.JButton();
        exibirButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelNumero = new javax.swing.JLabel();
        jLabelMaior = new javax.swing.JLabel();
        jLabelMenor = new javax.swing.JLabel();
        jLabelMedia = new javax.swing.JLabel();
        jLabelValores = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        opcoesCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Somar", "Multiplicar" }));

        calcularButton.setText("Calcular");

        OKButton.setText("OK");

        exibirButton.setText("Exibir");

        jLabel1.setText("Programa JFrame");

        jLabelNumero.setText("Digite o numero:");

        jLabelMaior.setText("Maior >>>");

        jLabelMenor.setText("Menor >>>");

        jLabelMedia.setText("Média >>>");

        jLabelValores.setText("Valores:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelMenor)
                                        .addComponent(jLabelMedia))
                                    .addComponent(jLabelMaior, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelValores, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maiorText)
                            .addComponent(valoresText)
                            .addComponent(menorText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mediaText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(opcoesCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(calcularButton, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(exibirButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numeroText, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(OKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabelNumero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OKButton))
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMaior)
                    .addComponent(maiorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMenor)
                    .addComponent(menorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exibirButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMedia)
                    .addComponent(mediaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValores)
                    .addComponent(valoresText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcoesCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calcularButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKButton;
    private javax.swing.JButton calcularButton;
    private javax.swing.JButton exibirButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelMaior;
    private javax.swing.JLabel jLabelMedia;
    private javax.swing.JLabel jLabelMenor;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelValores;
    private javax.swing.JTextField maiorText;
    private javax.swing.JTextField mediaText;
    private javax.swing.JTextField menorText;
    private javax.swing.JTextField numeroText;
    private javax.swing.JComboBox<String> opcoesCB;
    private javax.swing.JTextField valoresText;
    // End of variables declaration//GEN-END:variables
}
